import type { Metadata } from "next";
import { Provider } from "@/components/ui/provider";
import { ClerkProvider } from "@clerk/nextjs";
import AppShell from "@/components/AppShell";

//! Update metadata to match your project
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "/manifest.webmanifest",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body>
          <Provider>
            <AppShell>{children}</AppShell>
          </Provider>
        </body>
      </html>
    </ClerkProvider>
  );
}
