name: Sync Fork

on:
  push:
    branches:
      - "sync-fork"
  schedule:
    - cron: '12 */1 * * *' # 12 minutes past the hour
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your forked repository
        uses: actions/checkout@v4
        with:
          repository: stopglobalwarmingdaily/stop-global-warming-daily
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/hack4impact-calpoly/stop-global-warming-daily.git
          git fetch upstream

      - name: Sync with upstream/develop
        run: |
          git fetch upstream develop
          git checkout -B develop origin/develop
          git merge upstream/develop --no-edit
          git push origin develop

      - name: Clean up
        run: |
          git remote remove upstream